galaxy_info:
  role_name: tools
  description: Setup for test servers
  author: Aleksei Kutsenko
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
