galaxy_info:
  role_name: essential
  description: Setup server essentials
  author: Aleksei Kutsenko
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
